version: '1.0.0'
name: 'svelte-prod'

services:
  svelte-prod:
    build:
      # To define current workdir using context
      context: ..
      dockerfile: dockerfiles/Dockerfile.svelteapp_prod
    ports:
      - '3000:3000'
